version: "3.8"

services:
  postgres:
    restart: always
    image: postgres:14.5
    expose:
      - 5432
    env_file:
      - app/app/.env
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./dumps:/code/dumps

  backend:
    restart: always
    container_name: shop-django
    build: ./app
    command: bash -c "
      python manage.py migrate &&
      gunicorn -w 3 app.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - ./app:/app
    expose:
      - 8000
    depends_on:
      - postgres

  celery:
    restart: always
    build: ./app
    command: celery -A app worker -B -l INFO
    volumes:
      - ./app:/app
    depends_on:
      - postgres

  redis:
    image: redis:7.0.4
    expose:
      - 6379

  nginx:
    build: nginx
    ports:
      - "8200:80"
    depends_on:
      - backend
