version: "3.8"

services:
  postgres:
    image: postgres:14.5
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./dumps:/code/dumps
    env_file:
      - app/app/.env

  redis:
    image: redis:7.0.4
    ports:
      - "6379:6379"
