# Generated by Django 4.1.2 on 2022-11-03 12:04

from django.db import migrations


def apply_migration(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.bulk_create(
        [
            Group(name="Администратор"),
            Group(name="Кладовщик"),
            Group(name="Продавец"),
        ]
    )


def revert_migration(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(
        name__in=[
            "Администратор",
            "Кладовщик",
            "Продавец",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [migrations.RunPython(apply_migration, revert_migration)]
