# Generated by Django 4.1.2 on 2022-10-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_rename_description_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(
                default="test", max_length=31, verbose_name="Артикул"
            ),
            preserve_default=False,
        ),
    ]
