# Generated by Django 4.1.2 on 2022-10-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcode",
            name="id",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, verbose_name="Ключ"
            ),
        ),
    ]
