# Generated by Django 4.1.2 on 2022-10-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_barcode_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="barcode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="barcode",
            constraint=models.UniqueConstraint(
                fields=("product", "characteristic", "barcode"), name="unique_barcode"
            ),
        ),
    ]
