# Generated by Django 4.1.2 on 2022-10-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_productmovement_alter_barcode_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductMovement",
        ),
    ]
