# Generated by Django 4.1.2 on 2022-10-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_remove_productmovement_unique_movement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricechange",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Цена"),
        ),
    ]
